### ISSUE TITLE
The app don't run

### ISSUE THREAD

**Issue by micio86dev** [ptkdev-boilerplate/svelte-kit-ssr-boilerplate#7]
### Versions

-   **App Version:** v1.0.20210516
-   **Node Version:** v14.17.0
-   **Operating System:** macOS Monterey 12.0.1
-   **Browser:** Google Chrome v96.0.4664.55 (arm64)

### Expected Behavior

The app won't start, I updated `vite` but I receive an error in my browser on **http://127.0.0.1:5000**:

`Error: Unrecognized option 'enableSourcemap'
    at file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/svelte/compiler.mjs:29966:19
    at Array.forEach (<anonymous>)
    at validate_options (file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/svelte/compiler.mjs:29960:26)
    at compile (file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/svelte/compiler.mjs:30004:5)
    at compileSvelte2 (file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:313:20)
    at async TransformContext.transform (file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1460:27)
    at async Object.transform (/Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:42396:30)
    at async doTransform (/Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/kit/node_modules/vite/dist/node/chunks/dep-e0fe87f8.js:56801:29)`

### Actual Behavior

I receive this error:

> @ptkdev/svelte-kit-ssr-boilerplate@1.0.20210516 dev /Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit
svelte-kit dev -p 5000

`(node:4914) UnhandledPromiseRejectionWarning: file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/vite-plugin-svelte/dist/index.js:1117
  transformWithEsbuild
  ^^^^^^^^^^^^^^^^^^^^
SyntaxError: Named export 'transformWithEsbuild' not found. The requested module 'vite' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

> import pkg from 'vite';

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:104:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:149:5)
    at async Loader.import (internal/modules/esm/loader.js:177:24)
    at async file:///Users/alessandromicelli/Desktop/Progetti/Personali/Client/svelte-kit/node_modules/@sveltejs/kit/dist/cli.js:838:19
(Use `node --trace-warnings ...` to show where the warning was created)
(node:4914) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:4914) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

### Steps to Reproduce

1. clone the repo
2. switch to branch you want
3. launch `npm run init` 
4. launch `npm run dev`

**Comment by ptkdev** [comment]
Why you updated vite?
Svelte kit is really unstable, is in alpha status.
